title: vanRijn / MovingParts
description: Kinda like Batman, but with a wife and 3 kids

#theme: jekyll-theme-architect
# -- nice theme but no support for blogs?
#remote_theme: pages-themes/architect@v0.2.0
#remote_theme: "mmistakes/minimal-mistakes@4.28.0"
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-include-cache

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

search: true
