title: vanRijn / Moving Parts
description: Kinda like Batman, but with a wife and 3 kids

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

